export { default as UploadPage } from "./UploadPage";
export { default as LoginPage } from "./LoginPage";
export { default as AnalysisPage } from "./AnalysisPage";
export { default as SignupPage } from "./SignupPage";
export { default as ListPage } from "./ListPage";
export { default as HiddenPage } from "./HiddenPage";
export { default as IndelPage } from "./IndelPage";
export { default as MainPage } from "./MainPage";
export { default as IndelReportPage } from "./IndelReportPage";
